server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

spring:
  main:
    allow-circular-references: true

  datasource:
    jdbc-url: ${spring.db.url} # jdbc:oracle:thin:@namsuhwang.synology.me:1521:XE
    username: ${spring.db.user}
    password: ${spring.db.pwd}
    driver-class-name: oracle.jdbc.OracleDriver






